### ISSUE TITLE
[Fixed] The player will randomly be unable to respawn

### ISSUE THREAD

**Issue by Ayshie-God** [MLaroucheLaSalleMtl/7382-Team-D-2020#39] opened 2020-04-12 00:23 UTC
**Found:**
In Level_1, the player will randomly be unable to respawn

**Repro Steps:**
1 - Open Game using pressing Play from the preloader scene
2 - Reach Level_1
3 - Be killed by something in the level

**Note:**
This issue appears randomly at a low rate so it's likely to take multiple attempts before it actually occurs

**Actual Result:**
The Player dies and nothing happens
**Expected Result:**
The Player dies, and gets respawned

**Build:**
Commit 80
a088790

**Comment by YuYingLiWen** [comment] 2020-04-12 04:33
Yeah, this is is caused by the GameManager. It occurs in editor not sure if it occurs on a build version. 
If the repro rate is 1/5 or lower I will close it as won't fix for now.

**Comment by Ayshie-God** [comment] 2020-04-14 01:07
Just letting you know I made a build version of the current commit (commit 91 f64f27c94ab5b93eace28a6992ebb2f29cabbdf3 ) and the issue does occur in the build, currently it's occured everytime I've run the game

**Comment by YuYingLiWen** [comment] 2020-04-14 01:27
Sounds good, I will investigate further the issue. Thank you for the heads up!

**Comment by YuYingLiWen** [comment] 2020-04-15 05:42
Issue should have been fixed. In editor, it is broken as intended because the fix is not meant for the editor. Should be good on the next patch!

**Closed as completed** 2020-04-15 23:20 UTC
Labels: blocker, fixed
